### ISSUE TITLE
两个bug(?)

### ISSUE THREAD

**Issue by NobodyHere-rrr** [Glyceryl6/BetaBrewingSystem#2]
游戏版本：1.12.2
mod版本：1.4.5

bug1：
手持原版水瓶右键空酿造锅，水瓶会连水带瓶消失。

bug2：
可能会酿造出无效果的32767耐久的药水。
（第一种具体怎么酿的我忘了，但是第二种向含水酿造锅拿空瓶右键即可，拿一瓶再用水瓶右键（或用水淋在含水酿造锅上），锅中液体会变为白色，为同一种药水）
<img width="1276" alt="截屏2022-12-26 20 51 35" src="https://user-images.githubusercontent.com/62543054/209551742-9d8a9b21-72d9-4011-bf5a-5352f0b1cbb1.png">
<img width="442" alt="截屏2022-12-26 21 05 54" src="https://user-images.githubusercontent.com/62543054/209552164-6f4cea8f-63da-4c68-999d-6b7c10718739.png">
<img width="331" alt="截屏2022-12-26 21 15 07" src="https://user-images.githubusercontent.com/62543054/209552975-087d54ee-4cf8-4b20-98b3-aa8faaa049f4.png">

**Comment by Glyceryl6** [comment]
已收到反馈，目前Bug1已修复，Bug2正在修复中。至于日志为什么会飙升，可以附上你的运行日志，方便查找原因。

**Comment by Glyceryl6** [comment]
Bug2已修复

**Comment by NobodyHere-rrr** [comment]
日志数并不会飙升，问题已经查明是TexFix导致的，抱歉。
